apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
    - name: frontend
      image: rkalluru/d77-frontend
---
apiVersion: v1
kind: Pod
metadata:
  name: catalogue
spec:
  initContainers:
    - name: parameters-pull
      image: docker.io/rkalluru/d77-parameter-store-init-container-image
      imagePullPolicy: Always
      volumeMounts:
      - mountPath: /parameters
        name: parameters
      env:
        - name: PARAMS
          value: "dev.roboshop.docdb.endpoint,DOCDB_ENDPOINT dev.roboshop.docdb.username,DOCDB_USERNAME dev.roboshop.docdb.password,DOCDB_PASSWORD"
  containers:
    - name: catalogue
      image: rkalluru/d77-catalogue
      imagePullPolicy: Always
      volumeMounts:
      - mountPath: /parameters
        name: parameters
  volumes:
  - name: parameters
    emptyDir: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: user
spec:
  containers:
    - name: user
      image: rkalluru/d77-user
---
apiVersion: v1
kind: Pod
metadata:
  name: cart
spec:
  containers:
    - name: cart
      image: rkalluru/d77-cart
---
apiVersion: v1
kind: Pod
metadata:
  name: payment
spec:
  containers:
    - name: payment
      image: rkalluru/d77-payment
---
apiVersion: v1
kind: Pod
metadata:
  name: shipping
spec:
  containers:
    - name: shipping
      image: rkalluru/d77-shipping
---
apiVersion: v1
kind: Pod
metadata:
  name: dispatch
spec:
  containers:
    - name: dispatch
      image: rkalluru/d77-dispatch















